multi: False  # True if run multiple, interconnected brokers.

broker:
  hostname: "127.0.0.1" # "*"
  port: 5555

actor:
  hostname: "inproc://workers" # "*"
  port: 5556
  services:     # List the services here that the actor is capable of deploying.
    - "echo"