package service

import (
	mdapi_pb "github.com/Project-Auxo/Olympus/proto/mdapi"
	agent "github.com/Project-Auxo/Olympus/pkg/agent"

	// Import services that can be accessed by the loader here.
	"github.com/Project-Auxo/Olympus/pkg/service/echo"
)

// TODO: This file is supposed to be autogenerated.


// DispatchRequest will load a service from vantage point of the actor.
func DispatchRequest(
	client *agent.Client, requestProto *mdapi_pb.WrapperCommand) {
		serviceName := requestProto.GetRequest().GetServiceName()
		switch serviceName {
		// Client echo does ...
		case "echo":
			echo.ClientRequest(client, requestProto)
		}
}

// LoadService is used by the coordinator.
func LoadService(worker *agent.Worker, serviceName string,
	requestProto *mdapi_pb.WrapperCommand) (response *mdapi_pb.WrapperCommand) {
		checkService(serviceName)

		switch serviceName {
		// Actor echo does ...
		case "echo":
			response = echo.ActorResponse(worker, requestProto)
		}
		return
}
