package service

import (
	"github.com/Project-Auxo/Olympus/pkg/mdapi"

	// Import services that can be accessed by the loader here.
	"github.com/Project-Auxo/Olympus/pkg/service/echo"
)

// TODO: This file is supposed to be autogenerated.

// DispatchRequest will load a service from vantage point of the actor.
func DispatchRequest(
	client *mdapi.Mdcli, serviceName string, request []string) {
	checkService(serviceName)

	switch serviceName {
	// Client echo does ...
	case "echo":
		echo.ClientRequest(client, request)
	}
}

// LoadService is used by the coordinator.
func LoadService(worker *mdapi.Mdwrk, serviceName string, request []string) (
	response []string) {
	checkService(serviceName)

	switch serviceName {
	// Actor echo does ...
	case "echo":
		response = echo.ActorResponse(worker, request)
	}
	return
}
